opendatacube/datacube-charts

stable/datacube/README.md

Add some examples to get set up on a local mac environment
These are a first step and will be made more verbose in time.

Datacube documentation

---

deploy-charts.sh
stable/datacube-wps/Chart.yaml
stable/datacube-wps/values.yaml
stable/datacube/Chart.yaml
stable/datacube/requirements.yaml

Update default annotations in datacube-wps

Update Datacube chart requirements

---

stable/datacube-wps/Chart.yaml
stable/datacube-wps/templates/deployment.yaml
stable/datacube-wps/values.yaml

Use template from 'values' to set this so that the `values.yaml` file can set this value using a variable e.g. {{ .Values.domain }}

Add environment variable for WPS baseurl to deployment template.

---

stable/datacube/Chart.yaml
stable/datacube/requirements.yaml
stable/datacube/templates/wms-deployment.yaml
stable/datacube/values.yaml

Update datacube chart to be more compatible with standard helm chart notation for use with Flux

Datacube Chart Refactor for Flux

---

stable/datacube-dask/Chart.yaml
stable/datacube-dask/templates/worker-deployment.yaml
stable/datacube-dask/values.yaml

Adding datacube database connection variables to workers

Dask worker

---

deploy-charts.sh
stable/datacube/Chart.yaml
stable/datacube/requirements.yaml

Update requirements for datacube chart to use url

Update deploy-charts.sh script to handle remote repos

---

stable/datacube-processing/.helmignore
stable/datacube-processing/Chart.yaml
stable/datacube-processing/README.md
stable/datacube-processing/templates/_helpers.tpl
stable/datacube-processing/templates/processing-job.yaml
stable/datacube-processing/values.yaml

this chart creates a cron job that will check an sqs queue every 5 minutes, 
if there is data in in the queue it will filter and process it
if there is more data in the queue it will continue running, this provides a rough form of auto scaling as we can have multiple workers pulling jobs from a queue. when the queue empties all workers will stop as completed.
If a worker experiences an error the job that failed is returned to the queue.

add pipelines chart

---

stable/datacube/Chart.yaml
stable/datacube/requirements.yaml
stable/datacube/templates/NOTES.txt
stable/datacube/templates/_helpers.tpl
stable/datacube/templates/autoscaling.yaml
stable/datacube/templates/create-database-job.yaml
stable/datacube/templates/datacube-init-hook.yaml
stable/datacube/templates/dummy-cm.yaml
stable/datacube/templates/secrets.yaml
stable/datacube/templates/wms-deployment.yaml
stable/datacube/templates/wms-ingress.yaml
stable/datacube/templates/wms-service.yaml
stable/datacube/values.yaml

Remove psql sub chart from datacube
Allow specification of liveness and readiness probes in values
Remove global.externalDatabase
Add secretName template to remove if / else blocks
Cleanup values.yaml

Datacube Chart Updates

---

stable/datacube-dashboard/Chart.yaml
stable/datacube-dashboard/templates/deployment.yaml
stable/datacube-dashboard/templates/install-postgis.yaml
stable/datacube-dashboard/templates/service.yaml
stable/datacube-dashboard/templates/update_db.yaml
stable/datacube-dashboard/values.yaml

Following changes to `datacube-dashboard` chart:
1) Update chart version
2) Re-align spacing for `terminationGracePeriodSeconds` template variable
3) Update annotations and repository name in `values.yaml` file
4) Update metadata names in the template files

Automate cubedash db update on eks stack

---

stable/datacube/Chart.yaml
stable/datacube/templates/wms-deployment.yaml

enables  aws secrets to be used in wms instead of relying on sts

secret support

---

stable/datacube-dashboard/templates/update_creation_dt.yaml
stable/datacube-dashboard/templates/update_db.yaml
stable/datacube-dashboard/values.yaml

Add wms image for database datetime update

Pull wms image for db update

---

stable/datacube/Chart.yaml
stable/datacube/templates/wms-deployment.yaml
stable/datacube/values.yaml

this will allow us to seperate the ows from processing jobs

add affinity to ows

---

stable/datacube-wps/Chart.yaml
stable/datacube-wps/templates/deployment.yaml
stable/datacube-wps/values.yaml

- change httpget to exec curl, as there is a out of index error due to application expecting a proxy rather than a direct check.

Update wps to 0.7.6

---

stable/restcube/Chart.yaml
stable/restcube/templates/deployment.yaml

https://stackoverflow.com/questions/51717471/how-to-install-kubectl-in-kubernetes-container-through-docker-image
this solution is based on the stackoverflow answer.

Restcube kubectl

---

stable/datacube/Chart.yaml
stable/datacube/templates/wms-deployment.yaml
stable/datacube/values.yaml

I added pyspy to helm chart directly under container,

Add pyspy for ows

---

stable/datacube/Chart.yaml
stable/datacube/templates/wms-deployment.yaml
stable/datacube/values.yaml

Reverts opendatacube/datacube-charts#130

Revert "Add pyspy for ows"

---

stable/datacube-data/Chart.yaml
stable/datacube-data/templates/deployment.yaml
stable/datacube-data/values.yaml
stable/datacube-index/Chart.yaml
stable/datacube-index/templates/index.yaml
stable/datacube-index/values.yaml

Address WMS config mount as described in #137

Apply wms config mount pattern

---

stable/datacube-index/Chart.yaml
stable/datacube-index/templates/cronjob-index.yaml

Remove unsupported cronjob spec

---

stable/datacube-ows/.helmignore
stable/datacube-ows/Chart.yaml
stable/datacube-ows/README.md
stable/datacube-ows/templates/NOTES.txt
stable/datacube-ows/templates/_helpers.tpl
stable/datacube-ows/templates/autoscaling.yaml
stable/datacube-ows/templates/dummy-cm.yaml
stable/datacube-ows/templates/ows-deployment.yaml
stable/datacube-ows/templates/ows-ingress.yaml
stable/datacube-ows/templates/ows-service.yaml
stable/datacube-ows/templates/secrets.yaml
stable/datacube-ows/values.yaml

We'll clean up the other folder when this is migrated

Fix ows chart for v3

---

stable/datacube-wps/Chart.yaml
stable/datacube-wps/README.md
stable/datacube-wps/templates/deployment.yaml

https://github.com/opendatacube/datacube-wps/blob/master/docker/wps-entrypoint.sh
`$WPS_CONFIG_PATH` to mount external defined define `pywps.cfg`
`$DATACUBE_WPS_CONFIG_PATH` to mount external defined `datcube-wps-config.yaml`

Update wps chart to match latest code change

---

stable/datacube-wps/Chart.yaml
stable/datacube-wps/templates/deployment.yaml
stable/datacube-wps/templates/ingress.yaml

- updated deprecated api versions documented here https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

updated datacube-wps api versions

---

stable/datacube-data/Chart.yaml
stable/datacube-data/templates/deployment.yaml

upgrade API version as per guide here https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

updated kubernetes deprecated API version

---

stable/datacube-explorer/Chart.yaml
stable/datacube-explorer/templates/ingress.yaml
stable/datacube-ows/Chart.yaml
stable/datacube-ows/templates/ows-ingress.yaml
stable/datacube-wps/Chart.yaml
stable/datacube-wps/templates/ingress.yaml

my bad. reverted previous change for ingress - https://github.com/kubernetes/kubernetes/issues/90077

ingress is still serve using beta api version - revert previous change

---

stable/datacube-ows/Chart.yaml
stable/datacube-ows/templates/ows-deployment.yaml
stable/datacube-ows/values.yaml

- add pyspy as side container for ows container
- if pyspy is enabled give ows container additional security context

Add pyspy as side car for ows

---

stable/datacube-ows/Chart.yaml
stable/datacube-ows/templates/ows-deployment.yaml

- try adding securitycontext to pyspy container

Add securitycontext to pyspy

---

stable/datacube-explorer/Chart.yaml
stable/datacube-explorer/values.yaml

datacube-explorer: support node affinity config

datacube-explorer: support node affinity config

---

stable/datacube-ows/Chart.yaml
stable/datacube-ows/templates/ows-deployment.yaml
stable/datacube-ows/values.yaml

update ows helm to read image config properly. provide below config for image pull -
- registry
- repository
- tag

update ows helm to read image config properly

---

_config.yml
_data/versions.yaml
charts/index.yaml
index.md

Adds a Jekyll page to view the latest  helm package versions
https://github.com/opendatacube/datacube-charts/tree/gh-pages/charts

Adds index.md for Github pages

---

stable/datacube-explorer/Chart.yaml
stable/datacube-explorer/templates/ingress.yaml
stable/datacube-explorer/templates/update_creation_dt.yaml
stable/datacube-explorer/values.yaml

- cleanup explorer chart - remove unused config
- updated explorer ingress similar to `datacube-ows` ingress config template

Update explorer chart

---

.mergify.yml
stable/datacube-explorer/Chart.yaml
stable/datacube-explorer/templates/ingress.yaml

- fix explorer ingress config - serviceport
- update mergify rules

Fix explorer ingress

---

stable/datacube-explorer/Chart.yaml
stable/datacube-explorer/templates/ingress.yaml

- datacube-explore ingress helm not happy so try this

try declare fullname

---

stable/datacube-ows/Chart.yaml
stable/datacube-ows/templates/ows-deployment.yaml

enable mounting entire cfg folder with multiple ows_cfg parts.

enable mounting cfg folder

---

stable/datacube-wps/Chart.yaml
stable/datacube-wps/templates/hpa.yaml
stable/datacube-wps/values.yaml

Adds horizontal pod scaling capability and helm 3 compatibility

Adds HPA config and helm 3 compatibility

---

stable/datacube-explorer/Chart.yaml
stable/datacube-explorer/templates/update_creation_dt.yaml
stable/datacube-explorer/values.yaml

use backoffLimit and concurrencyPolicy to reduce retries with cronjob

added backoffLimit to update-creation-dt cron job

---

.github/workflows/lint.yml
ct-config.yaml

add chart test to datacube-chart

---

stable/datacube-ows/Chart.yaml
stable/datacube-ows/templates/ows-deployment.yaml
stable/datacube-ows/values.yaml

Adds tolerations capability to ows deployment

Add tolerations to ows deployment

---

stable/datacube-wps/Chart.yaml
stable/datacube-wps/templates/deployment.yaml

Enable the Docker registry option for WPS so we can pull from ECR.

Enable registry option for ECR

---

stable/datacube-wps/Chart.yaml
stable/datacube-wps/README.md
stable/datacube-wps/templates/deployment.yaml
stable/datacube-wps/values.yaml

Updates to the WPS deployment.yaml
- Adds securityContext
- Adds serviceAccountName
- Includes updates to default values, adds default resource requests

Enable securityContext and serviceAccountName for WPS

---

stable/datacube-ows/Chart.yaml
stable/datacube-ows/README.md
stable/datacube-ows/templates/autoscaling.yaml
stable/datacube-ows/values.yaml

migrate to v2beta2 for more customisations https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

update hpa for ows to v2beta2

---

stable/datacube-ows/Chart.yaml
stable/datacube-ows/README.md
stable/datacube-ows/templates/autoscaling.yaml

invalid type for io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerSpec.metrics: got "map", expected "array"

fix invalid type

---

stable/datacube-explorer/Chart.yaml
stable/datacube-explorer/README.md
stable/datacube-explorer/templates/deployment.yaml
stable/datacube-explorer/values.yaml

Fixes: #221 
potentially fix: https://github.com/opendatacube/datacube-explorer/issues/495

add checksum to explorer deployment

---

stable/datacube-dask/README.md
stable/datacube-data/README.md
stable/datacube-dev-env/README.md
stable/datacube-explorer/README.md
stable/datacube-index/Chart.yaml
stable/datacube-index/README.md
stable/datacube-ows/README.md
stable/datacube-processing/README.md
stable/datacube-wps/README.md
stable/datakubemanager/README.md
stable/restcube/README.md

- update cmd
- update docs with latest cmd

upgrade helm-docs cmd

---

stable/datacube-ows/Chart.yaml

Looking the the GH actions this should cause a new helm package to be available.

Bump OWS chart version

---

stable/datacube-explorer/templates/ingress.yaml

Support newer recommended way to associate an ingress with an ingress class.

Add ALB class name to Explorer chart

---

stable/datacube-explorer/templates/ingress.yaml

Reverting changes as the chart version number wasn't incremented

revert changes
