- stable/datacube-dashboard/Chart.yaml
- stable/datacube-dashboard/templates/install-postgis.yaml
Update Datacube Dashboard  to not require state-bucket variable that is no longer used.
> Remove state-bucket variable

- stable/datacube-wps/Chart.yaml
- stable/datacube-wps/templates/deployment.yaml
- stable/datacube-wps/values.yaml
Update datacube-wps chart to use more standard terminology for docker image configuration. Seperate out nested wps.config values to top level wps-config for better compatibility in subcharts with flux
> WPS Chart Refactor for Flux Compatibility

- stable/datacube/Chart.yaml
- stable/datacube/templates/autoscaling.yaml
- stable/datacube/templates/wms-deployment.yaml
- stable/datacube/templates/wms-ingress.yaml
- stable/datacube/templates/wms-service.yaml
with this change datacube databases can be created using this helm chart without a wms.
> Make wms templates optional based on a wms.enabled flag 

- stable/datacube/Chart.yaml
- stable/datacube/templates/dummy-cm.yaml
stops Helm emitting an error message which can interfere with CI / CD tools
> Add Dummy Config map when WMS is not enabled

- stable/datacube-dashboard/Chart.yaml
- stable/datacube-dashboard/templates/deployment.yaml
- stable/datacube-dashboard/templates/install-postgis.yaml
- stable/datacube-dashboard/templates/update_db.yaml
- stable/datacube-dashboard/values.yaml
Allow secretName and adminSecretName to be set as values to use as the name for secretKeyRefs for DB and ADMIN DB usernames and passwords
> Allow secretKeyRefs name overrides in datacube-dashboard

- stable/datacube-dashboard/Chart.yaml
- stable/datacube-dashboard/templates/install-postgis.yaml
Prevents helm / tiller entering a state which is unrecoverable automatically by flux.
> postgis install to run as a job instead of hook

- stable/datacube/Chart.yaml
- stable/datacube/templates/wms-ingress.yaml
before this change:
```
ingress:
annotations:
kubernetes.io/ingress.class: alb
alb.ingress.kubernetes.io/scheme: internet-facing
```
-> 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
annotations:
kubernetes.io/ingress.class: alb
alb.ingress.kubernetes.io/scheme: internet-facing
```
because the indentation is wrong it get's ignored by kubernetes
after this change
-> 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
annotations:
kubernetes.io/ingress.class: alb
alb.ingress.kubernetes.io/scheme: internet-facing
```
> fix ingress annotation indentation

- stable/datacube-index/Chart.yaml
- stable/datacube-index/README.md
- stable/datacube-index/templates/archive.yaml
- stable/datacube-index/templates/cronjob-index.yaml
- stable/datacube-index/templates/index.yaml
- stable/datacube-index/values.yaml
Update index chart to not use global.externalDatabase
index chart does not use index.jobname to name create jobs
archive cronjob is now disabled by default and will not be created
Add instructions to README.md for indexing multiple x_ folders in dea-public-data using parallel helm jobs
> Index chart updates

- stable/datacube-dask/Chart.yaml
- stable/datacube-dask/templates/worker-deployment.yaml
I think this is the best way to do it. I can't imagine one wanting the dask worker to not run the dask worker command.
Another enhancement would be to use the entrypoint as the default `command`.
> update worker args to explicitly include `dask-worker`

- stable/datacube-dask/Chart.yaml
- stable/datacube-dask/templates/worker-deployment.yaml
This change ensures both can be seperated, and should allow hpa to determine current worker cpu stats
> selector for worker matched both worker and scheduler causing issues with hpa

- stable/datacube-dashboard/Chart.yaml
- stable/datacube-dashboard/templates/update_creation_dt.yaml
- stable/datacube-dashboard/values.yaml
**Background:**
`Cubedash` `Summary` `Generation` throws an exception if datasets `Creation time` (by default: `'creation_dt'` in the `yaml`) is `Null`. Because of this error, `product`/`datasets` would not be updated or added to the explorer dashboard.
**Fix for the issue described above:**
- Add `datacube dashboard` `template` to automate `explorer` `summary` `generation` that would setup a `cron` `job` to  update the `creation dt`
> Automate explorer indexing

- stable/datacube-dashboard/Chart.yaml
- stable/datacube-dashboard/templates/deployment.yaml
- stable/datacube-dashboard/templates/install-postgis.yaml
- stable/datacube-dask/Chart.yaml
- stable/datacube-dask/templates/deployment.yaml
- stable/datacube-dask/templates/worker-deployment.yaml
- stable/datacube-data/Chart.yaml
- stable/datacube-data/templates/deployment.yaml
- stable/datacube-index/Chart.yaml
- stable/datacube-index/templates/archive.yaml
- stable/datacube-index/templates/cronjob-index.yaml
- stable/datacube-index/templates/index.yaml
- stable/datacube-processing/Chart.yaml
- stable/datacube-processing/templates/processing-job.yaml
- stable/datacube-wps/Chart.yaml
- stable/datacube-wps/templates/deployment.yaml
- stable/datacube/Chart.yaml
- stable/datacube/templates/create-database-job.yaml
- stable/datacube/templates/datacube-init-hook.yaml
- stable/datacube/templates/wms-deployment.yaml
- stable/restcube/Chart.yaml
- stable/restcube/templates/celery-worker-deployment.yaml
- stable/restcube/templates/deployment.yaml
DNS resolver sends out two DNS requests, one for the `A (ipv4)` record and one for the `AAAA (ipv6)` record, on the same port. This is the default since `glbc 2.9` to do them in parallel. Intermittently, `A` record is returned almost immediately whereas `AAAA` record timeouts after some while, causing the library to think that overall lookup has timed out. This causes `libc` to retry after waiting for 5 seconds. Thus causing `dns` resolution to be delayed by multiple of 5 seconds.
Turn on `single-request-reopen` (since glibc 2.9) `dnsConfig` option fixes issue with the `dns` resolver using the same socket for the `A` and `AAAA` requests. 
Some hardware mistakenly sends back only one reply. When that happens the client system will sit and wait for the second reply. Turning this option on …
> Turn on single-request-reopen option to fix intermittent delays

- stable/datacube-dashboard/Chart.yaml
- stable/datacube-dashboard/templates/update_creation_dt.yaml
Following are the updates within this PR:
- Add admin credentials to docker environment to allow automated script to create new database for cubedash processing
- Add AWS credentials to docker environment to allow automated script to push sns notification
> Add credentials in the docker env

- stable/datacube-dashboard/Chart.yaml
- stable/datacube-dashboard/templates/service.yaml
- stable/datacube-dask/Chart.yaml
- stable/datacube-dask/templates/service.yaml
- stable/datacube-dev-env/Chart.yaml
- stable/datacube-dev-env/templates/service.yaml
- stable/datacube-wps/Chart.yaml
- stable/datacube-wps/templates/service.yaml
- stable/datacube/Chart.yaml
- stable/datacube/templates/wms-service.yaml
Add annotation support to all services that don't have it, 
This will be used to enable us to share a single ALB and have different health-checks per service.
> Service annotation

- stable/datacube-dashboard/Chart.yaml
- stable/datacube-dashboard/templates/ingress.yaml
- Remove ingress tls as we are not using it
- Add rules to use `alb.ingress.kubernetes.io/actions.${action-name}` annotation ingress setup to redirect http traffic into https
> Fix alb redirect issue

- stable/datacube-explorer/Chart.yaml
- stable/datacube-explorer/templates/ingress.yaml
datacube-explorer - update deprecated kubernetes API version as per guide here - https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
> datacube-explorer - update deprecated kubernetes API version

- stable/datacube-explorer/Chart.yaml
- stable/datacube-explorer/templates/ingress.yaml
- stable/datacube-ows/Chart.yaml
- stable/datacube-ows/templates/ows-ingress.yaml
- stable/datacube-wps/Chart.yaml
- stable/datacube-wps/templates/ingress.yaml
We are good to use stable API version for ingress as per this doc: https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html
> upgrade ingress API verion to stable API - networking.k8s.io/v1

- stable/datacube-ows/Chart.yaml
- stable/datacube-ows/templates/ows-deployment.yaml
https://v1-16.docs.kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/
needed to allow namespacesharing for pyspy sidecar to access the process in main ows container
> Allow pyspy to access ows containers process

- stable/datacube-explorer/Chart.yaml
- stable/datacube-explorer/templates/ingress.yaml
fix ingress manifest as we have remove support for `.Values.global` attributes from `datacube-explorer` chart. This is currently breaking deployments
> Fix explorer ingress helm manifest

- stable/datacube-ows/templates/ows-deployment.yaml
The add-service-account-support branch looks like it is WIP and is also broken so far as my testing was concerned.
I've patched the branch to place the service account spec where I believe it was intended to be in the WIP branch.
Would also like to see the WIP branch made into a PR but will wait until this patch PR is approved first.
> patch sa spec in deployment

- README.md
- stable/datacube-wps/Chart.yaml
- stable/datacube-wps/README.md
- stable/datacube-wps/values.yaml
Specifying "exec" (for the shell to invoke `curl`) conflicts with being able to specify "httpGet" (native probe).
This relates to https://github.com/opendatacube/datacube-wps/issues/129
This probe formulation was already a bit broken because `curl` does not return nonzero exit code upon a server 500 response unless you include the `--fail` argument. It seems cleaner to admit the _native_ kubernetes syntax for a http probe.
> Unspecify WPS liveness probe

- stable/datacube-wps/Chart.yaml
- stable/datacube-wps/README.md
- stable/datacube-wps/templates/ingress.yaml
Some deployments may wish to host multiple services on different paths of _the same host domain_, which requires configuring the precedence order of routing rules (so that the more-specific rule has priority over the root-path rule). 
If using AWS Load Balancer then rule priority is determined by alphabetical sorting of the ingress names. (This is documented as _implicit_ ordering; the _explicit_ alternative is to manually assign a unique rank to each ingress individually, however reassigning rank integers requires a separate deallocation step that is incongruent with "infrastructure as code". The implicit approach seems far more maintainable for cases with several ingresses in the same routing group.) Hence, require an option to customise the ingress name, to facilitate configuring the …
> Parameterise WPS ingress name

- stable/datacube-wps/Chart.yaml
- stable/datacube-wps/README.md
- stable/datacube-wps/templates/hpa.yaml
autoscaler/v2beta1 was deprecated in kubernetes v1.19
> Update WPS hpa to v2beta2

- stable/datacube-ows/Chart.yaml
- stable/datacube-ows/README.md
- stable/datacube-ows/templates/ows-deployment.yaml
Intended to ensure that requests can drain when pods terminating.
See https://github.com/opendatacube/datacube-ows/issues/764
> OWS: Add pre-stop delay

- .github/workflows/lint.yml
- stable/datacube-ows/Chart.yaml
- stable/datacube-ows/README.md
- stable/datacube-ows/templates/ows-deployment.yaml
- stable/datacube-ows/values.yaml
adding ows helm chart to ows documentation (https://github.com/opendatacube/datacube-ows/pull/898), while testing, the current helm fails to start. Updating helm chart to successfully start
This was tested by running 
```
helm install datacube-ows-local ./datacube-ows/ --values datacube-ows/values.yaml
```
- set profiling default to false
- add `ows_cfg` to `owsConfig` with default value integration test config file used in `datacube/ows`
- set default `owsConfig` image to `opendatacube/ows`
- add `path` to values.yaml
- remove unsupported environment variables `OWS_CONFIG_URL` and `OWS_CONFIG_PATH` as per this [pr](https://github.com/opendatacube/datacube-ows/pull/901)
- update `dockerArg` to use `datacube_ows.wsgi` instead of legacy `datacube_wms.wsgi`
- update github ci
> update datacube ows helm chart

- README.md
- stable/datacube-wps/Chart.yaml
- stable/datacube-wps/README.md
- stable/datacube-wps/templates/ingress.yaml
Required update for compatibility with current versions of Kubernetes.
(This is intended as a minimal change, to facilitate a re-deployment for testing and reassessment.)
See:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/
https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/
> Update WPS ingress to stable API version

- stable/datacube-dask/templates/worker-hpa.yaml
- stable/datacube-ows/templates/autoscaling.yaml
- stable/datacube-wps/templates/hpa.yaml
The v2betaX API versions were deprecated in Kubernetes 1.23 and are being removed in 1.26.
References:
- https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26
- https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/
> Update autoscaling API versions for HPA

- stable/datacube-ows/Chart.yaml
- stable/datacube-ows/README.md
- stable/datacube-ows/templates/ows-ingress.yaml
The recommended way to associate an ingress to an ingressclass is use the ingressClassName attribute in the spec, and no longer as an annotation
> Update ows chart to handle ingressClassName
